export enum IgrejaEnum {
  BARUERI = 'BARUERI',
  CARAPICUIBA = 'CARAPICUIBA',
  ANGELICA = 'JD ANGELICA',
  SAZANOV = 'JD SAZANOV',
  TONATO = 'JD TONATO',
  OSASCO = 'OSASCO',
  DIRCE = 'VL DIRCE',
}