export enum LayoutPlanilhaEnum {
  ID_COLUNA = 'A',
  IGREJA_COLUNA = 'B',
  CARGO_COLUNA = 'C',
  NOME_COLUNA = 'D',
  CPF_COLUNA = 'E',
  DATA_NASCIMENTO_COLUNA = 'F',
  STATUS_COLUNA = 'G',
  DATA_REGISTRO_COLUNA = 'H',
  JUSTIFICATIVA = 'I'
}